[package]
name = "cargo-test-all-features"
version = "1.0.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
edition = "2018"
description = "A Cargo subcommand to test all feature flag combinations"
repository = "https://github.com/frewsxcv/cargoo-test-all-features"
license = "MIT/Apache-2.0"

[dependencies]
cargo_metadata = "0.9"
serde_json = "1"
itertools = "0.9"
termcolor = "1"
